// config/tags.js
// Definición mínima de tags para PLC1
/*
=================================================================================
Cada tag será un objeto con estos campos:
=================================================================================
name → nombre lógico (para usar en el SCADA).
word → índice de registro (W0..W119).
bit → null si es la word completa, o número 0..15 si es un bit dentro de la word.
dir → "read" o "write".
desc → descripción corta (para tooltips, etiquetas, etc.).
cat → categoría (comandos, alarmas, temperatura… opcional pero útil).
=================================================================================
*/
// Tags mínimos para PLC1 con nombres claros (BTN, CMD, FBK, ALM)
const tags = [
  // --- Feedback de comandos Scada en W60 elaborados por el PLC, quien los escribe en la W0 ---
  { name: 'FBK_START_AUTO',             word: 0, bit: 0, dir: 'read',  desc: 'Pulsador físico Start Auto',            cat: 'Signal_Lamp' },
  { name: 'FBK_STOP_AUTO',              word: 0, bit: 1, dir: 'read',  desc: 'Pulsador físico Stop Auto',             cat: 'Signal_Lamp' },
  { name: 'FBK_STOP_STANDBY',           word: 0, bit: 2, dir: 'read',  desc: 'Stop Stand-by',                         cat: 'Signal_Lamp' },
  { name: 'FBK_PREP_TO_START',          word: 0, bit: 3, dir: 'read',  desc: 'Preparación para start UNA SEGA MD',    cat: 'Signal_Lamp' },
  { name: 'FBK_START_RESISTENZE',       word: 0, bit: 4, dir: 'read',  desc: 'Start resistencias (físico)',           cat: 'Signal_Lamp' },
  { name: 'FBK_STOP_RESISTENZE',        word: 0, bit: 5, dir: 'read',  desc: 'Stop resistencias (físico)',            cat: 'Signal_Lamp' },
  { name: 'FBK_START_POMPAOLEO',        word: 0, bit: 6, dir: 'read',  desc: 'Start central hidráulica (físico)',     cat: 'Signal_Lamp' },
  { name: 'FBK_STOP_POMPAOLEO',         word: 0, bit: 7, dir: 'read',  desc: 'Stop central hidráulica (físico)',      cat: 'Signal_Lamp' },
  
  { name: 'FBK_PULS_MANUAL',            word: 0, bit: 8, dir: 'read',  desc: 'FBK_PULS_MANUAL',                       cat: 'Signal_Lamp' },
  { name: 'FBK_PULS_AUTO',              word: 0, bit: 9, dir: 'read',  desc: 'FBK_PULS_AUTO',                         cat: 'Signal_Lamp' },
  { name: 'FBK_RESET_CONT_PROD',        word: 0, bit: 10, dir: 'read',  desc: 'FBK_RESET_CONT_PROD',                  cat: 'Signal_Lamp' },
  { name: 'FBK_RESET_STOP_AUTO_A_CIL',  word: 0, bit: 11, dir: 'read',  desc: 'FBK_RESET_STOP_AUTO_A_CIL',            cat: 'Signal_Lamp' },
  { name: 'FBK_ABIL_START_AUTO_A_RES',  word: 0, bit: 12, dir: 'read',  desc: 'FBK_ABIL_START_AUTO_A_RES',            cat: 'Signal_Lamp' },
  { name: 'FBK_ABIL_STOP_AUTO_A_TEMPO', word: 0, bit: 13, dir: 'read',  desc: 'FBK_ABIL_STOP_AUTO_A_TEMPO',           cat: 'Signal_Lamp' },
  { name: 'FBK_ABIL_STOP_AUTO_A_CICLI', word: 0, bit: 14, dir: 'read',  desc: 'FBK_ABIL_STOP_AUTO_A_CICLI',           cat: 'Signal_Lamp' },
  { name: 'W0_BIT15_NO_USAR',           word: 0, bit: 15, dir: 'read',  desc: 'W0_BIT15_NO_USAR',                     cat: 'Signal_Lamp' },
  
  // --- Feedback de comandos Scada en W61 elaborados por el PLC, quien los escribe en la W1 ---
  { name: 'FBK_CICLO_AUTO-MAN',         word: 1, bit: 0, dir: 'read',  desc: 'FBK_CICLO_AUTO-MAN',                    cat: 'Signal_Lamp' },
  { name: 'FBK_RESET_ANOMALIE',         word: 1, bit: 1, dir: 'read',  desc: 'FBK_RESET_ANOMALIE',                    cat: 'Signal_Lamp' },
  { name: 'FBK_AUTO_SIS_INGRASSAGGIO',  word: 1, bit: 2, dir: 'read',  desc: 'FBK_AUTO_SIS_INGRASSAGGIO',             cat: 'Signal_Lamp' },
  { name: 'FBK_W1_BIT3_FREE',           word: 1, bit: 3, dir: 'read',  desc: 'FBK_W1_BIT3_FREE',                      cat: 'Signal_Lamp' },
  { name: 'FBK_W1_BIT4_FREE',           word: 1, bit: 4, dir: 'read',  desc: 'FBK_W1_BIT4_FREE',                      cat: 'Signal_Lamp' },
  { name: 'FBK_W1_BIT5_FREE',           word: 1, bit: 5, dir: 'read',  desc: 'FBK_W1_BIT5_FREE',                      cat: 'Signal_Lamp' },
  { name: 'FBK_RESISTENZE_ACCESE',      word: 1, bit: 6, dir: 'read',  desc: 'FBK_RESISTENZE_ACCESE',                 cat: 'Signal_Lamp' },
  { name: 'FBK_POMPA_ACCESA',           word: 1, bit: 7, dir: 'read',  desc: 'FBK_POMPA_ACCESA',                      cat: 'Signal_Lamp' },
																											          
  { name: 'FBK_MANUAL',                 word: 1, bit: 8, dir: 'read',  desc: 'FBK_MANUAL',                            cat: 'Signal_Lamp' },
  { name: 'FBK_START_CICLO',            word: 1, bit: 9, dir: 'read',  desc: 'FBK_START_CICLO',                       cat: 'Signal_Lamp' },
  { name: 'FBK_AUTOMATICO',             word: 1, bit: 10, dir: 'read',  desc: 'FBK_CICLO_AUTO-MAN',                   cat: 'Signal_Lamp' },
  { name: 'FBK_STOP_CICLO',             word: 1, bit: 11, dir: 'read',  desc: 'FBK_STOP_CICLO',                       cat: 'Signal_Lamp' },
  { name: 'FBK_W1_BIT12_FREE',          word: 1, bit: 12, dir: 'read',  desc: 'FBK_W1_BIT12_FREE',                    cat: 'Signal_Lamp' },
  { name: 'FBK_W1_BIT13_FREE',          word: 1, bit: 13, dir: 'read',  desc: 'FBK_W1_BIT13_FREE',                    cat: 'Signal_Lamp' },
  { name: 'FBK_W1_BIT14_FREE',          word: 1, bit: 14, dir: 'read',  desc: 'FBK_W1_BIT14_FREE',                    cat: 'Signal_Lamp' },
  { name: 'W1_BIT15_NO_USAR',           word: 1, bit: 15, dir: 'read',  desc: 'W1_BIT15_NO_USAR',                     cat: 'Signal_Lamp' },
  
  // --- VALORES DE PROCESO: PARAMETROS (palabras) ---
  { name: 'Spessore',                           word: 2, bit: null, dir: 'read', desc: 'Spessore Galleta',                    cat: 'Parametros' },
  { name: 'Spinta',                             word: 3, bit: null, dir: 'read', desc: 'Spinta Galleta',                      cat: 'Parametros' },
  { name: 'Cottura',                            word: 4, bit: null, dir: 'read', desc: 'Cottura Galleta',                     cat: 'Parametros' },
  { name: 'Espansione',                         word: 5, bit: null, dir: 'read', desc: 'Espansione Galleta',                  cat: 'Parametros' },
  { name: '2_Spinta',                           word: 6, bit: null, dir: 'read', desc: '2_Spinta Galleta',                    cat: 'Parametros' },
  { name: '2_Cottura',                          word: 7, bit: null, dir: 'read', desc: '2_Cottura Galleta',                   cat: 'Parametros' },
  { name: '2_Espansione',                       word: 8, bit: null, dir: 'read', desc: '2_Espansione Galleta',                cat: 'Parametros' },
  { name: 'Dosat_Tpo_di_Pulizia',               word: 9, bit: null, dir: 'read', desc: 'Dosatori Tempo di Pulizia',           cat: 'Parametros' },
  { name: 'Dosat_Pulizia_Ritardo',              word: 10, bit: null, dir: 'read', desc: 'Dosatori Pulizia Ritardo',           cat: 'Parametros' },
  { name: 'Rit_Salita_Piastra_CentCicloDoppio', word: 11, bit: null, dir: 'read', desc: 'Rit_Salita_Piastra_CentCicloDoppio', cat: 'Parametros' },
  { name: 'Bicchiere',                          word: 12, bit: null, dir: 'read', desc: 'Bicchiere',                          cat: 'Parametros' },
  { name: 'Dosatori _num_cicli_per_Pulizia',    word: 13, bit: null, dir: 'read', desc: 'Dosatori _num_cicli_per_Pulizia',    cat: 'Parametros' },
 
  // --- VALORES DE PROCESO: TEMPERATURA Y POTENCIA (palabras) ---
  { name: 'TEMP_SP_SUP',             word: 14, bit: null, dir: 'read', desc: 'Setpoint temperatura superior',                 cat: 'Temperatura' },
  { name: 'TEMP_SP_INF',             word: 15, bit: null, dir: 'read', desc: 'Setpoint temperatura inferior',                 cat: 'Temperatura' },
  { name: 'POT_PERC_SUP',            word: 16, bit: null, dir: 'read', desc: 'Potencia % superior',                           cat: 'Temperatura' },
  { name: 'POT_PERC_INF',            word: 17, bit: null, dir: 'read', desc: 'Potencia % inferior',                           cat: 'Temperatura' },
  { name: 'SERIAL_NUMBER_ENGI',      word: 18, bit: null, dir: 'read', desc: 'Serial Number Engi',                            cat: 'Parametros' }, 
  { name: 'CONSUMO_ENERG_ACTUAL',    word: 19, bit: null, dir: 'read', desc: 'Consumo energético actual',                     cat: 'Energia' },
  { name: 'CONSUMO_MEDIO_DIA',       word: 20, bit: null, dir: 'read', desc: 'Consumo medio diario',                          cat: 'Energia' },
  { name: 'POT_MEDIA_SUP',           word: 21, bit: null, dir: 'read', desc: 'Potencia media superior',                       cat: 'Energia' },
  { name: 'POT_MEDIA_INF',           word: 22, bit: null, dir: 'read', desc: 'Potencia media inferior',                       cat: 'Energia' },
  { name: 'TPO_RETARDO_AL_START',    word: 23, bit: null, dir: 'read', desc: 'Tempo ritardo allo start',                      cat: 'Tiempos' },
  { name: 'TEMP_MOLDE_SUP',          word: 24, bit: null, dir: 'read', desc: 'Temperatura real estampo superior',             cat: 'Temperatura' },
  { name: 'TEMP_MOLDE_INF',          word: 25, bit: null, dir: 'read', desc: 'Temperatura real estampo inferior',             cat: 'Temperatura' },
  { name: 'RETARDO_AL_INICIO',       word: 26, bit: null, dir: 'read', desc: 'Ritardo alla partenza',                         cat: 'Tiempos' },
  { name: 'NUMERO_DE_FORMAS',        word: 27, bit: null, dir: 'read', desc: 'NUMERO DE FORMAS',                              cat: 'parametros' },
  { name: 'RES_1_NVO_PARAM_RECETA',  word: 28, bit: null, dir: 'read', desc: 'RESERVA 1 NUEVO PARAM RECETA',                  cat: 'recetas' },
  { name: 'RES_2_NVO_PARAM_RECETA',  word: 29, bit: null, dir: 'read', desc: 'RESERVA 2 NUEVO PARAM RECETA',                  cat: 'recetas' },
  { name: 'RES_3_NVO_PARAM_RECETA',  word: 30, bit: null, dir: 'read', desc: 'RESERVA 3 NUEVO PARAM RECETA',                  cat: 'recetas' },
  { name: 'HORA_START_AUTOM_RES',    word: 31, bit: null, dir: 'read', desc: 'HORA START AUTOMATICO RES PROG',                cat: 'Tiempos' },
  { name: 'MIN_START_AUTOM_RES',     word: 32, bit: null, dir: 'read', desc: 'MINUTO START AUTOMATICO RES PROG',              cat: 'Tiempos' },
  { name: 'HABILITA_START_xDIAS',    word: 33, bit: null, dir: 'read', desc: 'Abilitazione Start (1-7 giorni + 8 tutti)',     cat: 'Tiempos' },
  { name: 'DESHABILITA_START_xDIAS', word: 34, bit: null, dir: 'read', desc: 'Disabilitazione Start (1-7 giorni + 8 tutti)',  cat: 'Tiempos' },
  { name: 'HORA_STOP_PROGRAMADO',    word: 35, bit: null, dir: 'read', desc: 'Ora stop macchina programmata',                 cat: 'Tiempos' },
  { name: 'MINUTO_STOP_PROGRAMADO',  word: 36, bit: null, dir: 'read', desc: 'Ora stop macchina programmata',                 cat: 'Tiempos' },
  { name: 'HABILITA_STOP_xDIAS',     word: 37, bit: null, dir: 'read', desc: 'Abilitazione Stop (1-7 giorni + 8 tutti)',      cat: 'Tiempos' },
  { name: 'DESHABILITA_STOP_xDIAS',  word: 38, bit: null, dir: 'read', desc: 'Disabilitazione Stop (1-7 giorni + 8 tutti)',   cat: 'Tiempos' },
  { name: 'SET_NUM_CICLOS_AL_STOP',  word: 39, bit: null, dir: 'read', desc: 'Numero di cicli allo stop (set cicli)',         cat: 'Tiempos' },
  { name: 'CONT_NUM_CICLOS_AL_STOP', word: 40, bit: null, dir: 'read', desc: 'Conteggio cicli allo stop (count down)',        cat: 'Tiempos' },

  { name: 'STATO_MACCHINA',          word: 43, bit: null, dir: 'read', desc: 'STATO_MACCHINA',                     cat: 'Produccion' },
  { name: 'TEMPO_CICLO_ULTIMO',      word: 44, bit: null, dir: 'read', desc: 'Tiempo ciclo (último)',              cat: 'Produccion' },
  { name: 'PROD_ACTUAL_GOLPES',      word: 45, bit: null, dir: 'read', desc: 'Producción actual (golpes)',         cat: 'Produccion' },
  { name: 'ANNO',                    word: 46, bit: null, dir: 'read', desc: 'Anno',                               cat: 'Data' },
  { name: 'MESSE',                   word: 47, bit: null, dir: 'read', desc: 'Messe',                              cat: 'Data' },
  { name: 'GIORNO',                  word: 48, bit: null, dir: 'read', desc: 'Giorno',                             cat: 'Data' },
  { name: 'ORA',                     word: 49, bit: null, dir: 'read', desc: 'Ora',                                cat: 'Data' },
  { name: 'MINUTo',                  word: 50, bit: null, dir: 'read', desc: 'Minuto',                             cat: 'Data' },
  { name: 'W51_FREE',                word: 51, bit: null, dir: 'read', desc: 'W51_Free',                           cat: 'Free' },

  // --- ALARMAS (feedback) ---
  // --- W52 ---
  { name: 'EMERGENZA_PREMUTA',       word: 52, bit: 0, dir: 'read',  desc: 'EMERGENZA_PREMUTA',                    cat: 'Alarma' },
  { name: 'TERMICO_RES_SUP_INTERV',  word: 52, bit: 1, dir: 'read',  desc: 'TERMICO_RES_SUP_INTERV',               cat: 'Alarma' },
  { name: 'TERMICO_RES_INF_INTERV',  word: 52, bit: 2, dir: 'read',  desc: 'TERMICO_RES_INF_INTERV',               cat: 'Alarma' },
  { name: 'TERMICO_CENT_IDR_INTERV', word: 52, bit: 3, dir: 'read',  desc: 'TERMICO_CENT_IDR_INTERV',              cat: 'Alarma' },
  { name: 'RIPARI_APERTI',           word: 52, bit: 4, dir: 'read',  desc: 'RIPARI_APERTI',                        cat: 'Alarma' },
  { name: 'CENT_IDRAULICA_SPENTA',   word: 52, bit: 5, dir: 'read',  desc: 'CENT_IDRAULICA_SPENTA',                cat: 'Alarma' },
  { name: 'KO_AV_PIASTRA_CENT_SUP',  word: 52, bit: 6, dir: 'read',  desc: 'KO_AV_PIASTRA_CENT_SUP',               cat: 'Alarma' },
  { name: 'KO_AV_STAMPOINF_NOINPOS', word: 52, bit: 7, dir: 'read',  desc: 'KO_AV_STAMPOINF_NOINPOS',              cat: 'Alarma' },
  { name: 'KO_AV_VAL_SCAR_NOINPOS',  word: 52, bit: 8, dir: 'read',  desc: 'KO_AV_VAL_SCAR_NOINPOS',               cat: 'Alarma' },
  { name: 'KO_AV_SELET_IN_MANUALE',  word: 52, bit: 9, dir: 'read',  desc: 'KO_AV_SELET_IN_MANUALE',               cat: 'Alarma' },
  { name: 'CENT_IDR_SPENTA_IN_CICLO',word: 52, bit: 10, dir: 'read',  desc: 'CENT_IDR_SPENTA_IN_CICLO',            cat: 'Alarma' },
  { name: 'ANOM_MOV_SCARICO_GALLTE', word: 52, bit: 11, dir: 'read',  desc: 'ANOM_MOV_SCARICO_GALLTE',             cat: 'Alarma' },
  { name: 'ANOM_REED_CIL_SUPERIORE', word: 52, bit: 12, dir: 'read',  desc: 'ANOM_REED_CIL_SUPERIORE',             cat: 'Alarma' },
  { name: 'ANOM_REED_CIL_SCAR_GALL', word: 52, bit: 13, dir: 'read',  desc: 'ANOM_REED_CIL_SCAR_GALL',             cat: 'Alarma' },
  { name: 'TIMEOUT_MOVIMENTI',       word: 52, bit: 14, dir: 'read',  desc: 'TIMEOUT_MOVIMENTI',                   cat: 'Alarma' },
  { name: 'W52_BIT15_NO_USAR',       word: 52, bit: 15, dir: 'read',  desc: 'W52_BIT15_NO_USAR',                   cat: 'No Usar' },
  // --- W53 ---
  { name: 'ALM_FINE_PRODOTTO',       word: 53, bit: 0, dir: 'read',  desc: 'ALM_FINE_PRODOTTO',                    cat: 'Alarma' },
  { name: 'ALM_CIL_NON_IN_POS_ALTA', word: 53, bit: 1, dir: 'read',  desc: 'ALM_CIL_NON_IN_POS_ALTA',              cat: 'Alarma' },
  { name: 'TEM_KO_ALLO_START_CICLO', word: 53, bit: 2, dir: 'read',  desc: 'TEM_KO_ALLO_START_CICLO',              cat: 'Alarma' },
  { name: 'ALM_PRESSIONE_ARIA',      word: 53, bit: 3, dir: 'read',  desc: 'ALM_PRESSIONE_ARIA',                   cat: 'Alarma' },
  { name: 'ALM_DISTRIB_GRASSO',      word: 53, bit: 4, dir: 'read',  desc: 'ALM_DISTRIB_GRASSO',                   cat: 'Alarma' },
  { name: 'ALM_LIVELLO_GRASSO',      word: 53, bit: 5, dir: 'read',  desc: 'ALM_LIVELLO_GRASSO',                   cat: 'Alarma' },
  { name: 'NON_SQ3_IN_FASE_DI_HOME', word: 53, bit: 6, dir: 'read',  desc: 'NON_SQ3_IN_FASE_DI_HOME',              cat: 'Alarma' },
  { name: 'NON_SQ5_IN_FASE_DI_HOME', word: 53, bit: 7, dir: 'read',  desc: 'NON_SQ5_IN_FASE_DI_HOME',              cat: 'Alarma' },
  { name: 'FINE_GARANZIA',           word: 53, bit: 8, dir: 'read',  desc: 'FINE_GARANZIA',                        cat: 'Alarma' },
  { name: 'START_STOP_ATTIVO',       word: 53, bit: 9, dir: 'read',  desc: 'START_STOP_ATTIVO',                    cat: 'Alarma' },
  { name: 'MANCA_SQ6',               word: 53, bit: 10, dir: 'read',  desc: 'MANCA_SQ6',                           cat: 'Alarma' },
  { name: 'DRY_CICLE_ATTIVO',        word: 53, bit: 11, dir: 'read',  desc: 'DRY_CICLE_ATTIVO',                    cat: 'Alarma' },
  { name: 'STOP_RES_RISCALD_100%',   word: 53, bit: 12, dir: 'read',  desc: 'STOP_RES_RISCALD_100%',               cat: 'Alarma' },
  { name: 'ALM_RISERVA_1',           word: 53, bit: 13, dir: 'read',  desc: 'ALM_RISERVA_1',                       cat: 'Alarma' },
  { name: 'ALM_RISERVA_2',           word: 53, bit: 14, dir: 'read',  desc: 'ALM_RISERVA_2',                       cat: 'Alarma' },
  { name: 'W53_BIT15_NO_USAR',       word: 53, bit: 15, dir: 'read',  desc: 'W53_BIT15_NO_USAR',                   cat: 'Alarma' },
  // --- W54 ---
  { name: 'ALM_RISERVA_3',           word: 54, bit: 0, dir: 'read',  desc: 'ALM_RISERVA_3',                        cat: 'Alarma' },
  { name: 'ALM_RISERVA_4',           word: 54, bit: 1, dir: 'read',  desc: 'ALM_RISERVA_4',                        cat: 'Alarma' },
  { name: 'ALM_RISERVA_5',           word: 54, bit: 2, dir: 'read',  desc: 'ALM_RISERVA_5',                        cat: 'Alarma' },
  { name: 'ALM_RISERVA_6',           word: 54, bit: 3, dir: 'read',  desc: 'ALM_RISERVA_6',                        cat: 'Alarma' },
  { name: 'ALM_RISERVA_7',           word: 54, bit: 4, dir: 'read',  desc: 'ALM_RISERVA_7',                        cat: 'Alarma' },
  { name: 'ALM_RISERVA_8',           word: 54, bit: 5, dir: 'read',  desc: 'ALM_RISERVA_8',                        cat: 'Alarma' },
  { name: 'ALM_RISERVA_9',           word: 54, bit: 6, dir: 'read',  desc: 'ALM_RISERVA_9',                        cat: 'Alarma' },
  { name: 'ALM_RISERVA_10',          word: 54, bit: 7, dir: 'read',  desc: 'ALM_RISERVA_10',                       cat: 'Alarma' },
  { name: 'ALM_RISERVA_11',          word: 54, bit: 8, dir: 'read',  desc: 'ALM_RISERVA_11',                       cat: 'Alarma' },
  { name: 'ALM_RISERVA_12',          word: 54, bit: 9, dir: 'read',  desc: 'ALM_RISERVA_12',                       cat: 'Alarma' },
  { name: 'ALM_RISERVA_13',          word: 54, bit: 10, dir: 'read',  desc: 'ALM_RISERVA_13',                      cat: 'Alarma' },
  { name: 'ALM_RISERVA_14',          word: 54, bit: 11, dir: 'read',  desc: 'ALM_RISERVA_14',                      cat: 'Alarma' },
  { name: 'ALM_RISERVA_15',          word: 54, bit: 12, dir: 'read',  desc: 'ALM_RISERVA_15',                      cat: 'Alarma' },
  { name: 'ALM_RISERVA_16',          word: 54, bit: 13, dir: 'read',  desc: 'ALM_RISERVA_16',                      cat: 'Alarma' },
  { name: 'ALM_RISERVA_17',          word: 54, bit: 14, dir: 'read',  desc: 'ALM_RISERVA_17',                      cat: 'Alarma' },
  { name: 'W54_BIT15_NO_USAR',       word: 54, bit: 15, dir: 'read',  desc: 'W54_BIT15_NO_USAR',                   cat: 'Alarma' },
  // --- W55 ---
  { name: 'ALM_RISERVA_19',          word: 55, bit: 0, dir: 'read',  desc: 'alarma_riserva_19',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_20',          word: 55, bit: 1, dir: 'read',  desc: 'alarma_riserva_20',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_21',          word: 55, bit: 2, dir: 'read',  desc: 'alarma_riserva_21',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_22',          word: 55, bit: 3, dir: 'read',  desc: 'alarma_riserva_22',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_23',          word: 55, bit: 4, dir: 'read',  desc: 'alarma_riserva_23',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_24',          word: 55, bit: 5, dir: 'read',  desc: 'alarma_riserva_24',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_25',          word: 55, bit: 6, dir: 'read',  desc: 'alarma_riserva_25',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_26',          word: 55, bit: 7, dir: 'read',  desc: 'alarma_riserva_26',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_27',          word: 55, bit: 8, dir: 'read',  desc: 'alarma_riserva_27',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_28',          word: 55, bit: 9, dir: 'read',  desc: 'alarma_riserva_28',                    cat: 'Alarma' },
  { name: 'ALM_RISERVA_29',          word: 55, bit: 10, dir: 'read',  desc: 'alarma_riserva_29',                   cat: 'Alarma' },
  { name: 'ALM_RISERVA_30',          word: 55, bit: 11, dir: 'read',  desc: 'alarma_riserva_30',                   cat: 'Alarma' },
  { name: 'ALM_RISERVA_31',          word: 55, bit: 12, dir: 'read',  desc: 'alarma_riserva_31',                   cat: 'Alarma' },
  { name: 'ALM_RISERVA_32',          word: 55, bit: 13, dir: 'read',  desc: 'alarma_riserva_32',                   cat: 'Alarma' },
  { name: 'ALM_RISERVA_33',          word: 55, bit: 14, dir: 'read',  desc: 'alarma_riserva_33',                   cat: 'Alarma' },
  { name: 'W55_BIT15_NO_USAR',       word: 55, bit: 15, dir: 'read',  desc: 'W55_BIT15_NO_USAR',                   cat: 'Alarma' },
  // ---
  // (añade aquí más ALM_..._FBK según las que realmente quieras vigilar tú)
   
  // --- W56 a W59 ---
  { name: 'W56_FREE',                word: 56, bit: null, dir: 'read', desc: 'W56_Free',                           cat: 'Free' },
  { name: 'W57_FREE',                word: 57, bit: null, dir: 'read', desc: 'W57_Free',                           cat: 'Free' },
  { name: 'W58_FREE',                word: 58, bit: null, dir: 'read', desc: 'W58_Free',                           cat: 'Free' },
  { name: 'W59_FREE',                word: 59, bit: null, dir: 'read', desc: 'W59_Free',                           cat: 'Free' },

  // --- COMANDOS DESDE SCADA (CMD_...) ---
  // Por simplicidad, los dejamos como words completas en la zona de escritura.
  
  // --- W60 ---
  // --- Comandos de Scada en W60 enviados al PLC, quien los elabora y escribe en la W0 ---
  { name: 'CMD_START_AUTO',             word: 60, bit: 0, dir: 'write',  desc: 'Pulsador físico Start Auto',            cat: 'Comandos' },
  { name: 'CMD_STOP_AUTO',              word: 60, bit: 1, dir: 'write',  desc: 'Pulsador físico Stop Auto',             cat: 'Comandos' },
  { name: 'CMD_STOP_STANDBY',           word: 60, bit: 2, dir: 'write',  desc: 'Stop Stand-by',                         cat: 'Comandos' },
  { name: 'CMD_PREP_TO_START',          word: 60, bit: 3, dir: 'write',  desc: 'Preparación para start UNA SEGA MD',    cat: 'Comandos' },
  { name: 'CMD_START_RESISTENZE',       word: 60, bit: 4, dir: 'write',  desc: 'Start resistencias (físico)',           cat: 'Comandos' },
  { name: 'CMD_STOP_RESISTENZE',        word: 60, bit: 5, dir: 'write',  desc: 'Stop resistencias (físico)',            cat: 'Comandos' },
  { name: 'CMD_START_POMPAOLEO',        word: 60, bit: 6, dir: 'write',  desc: 'Start central hidráulica (físico)',     cat: 'Comandos' },
  { name: 'CMD_STOP_POMPAOLEO',         word: 60, bit: 7, dir: 'write',  desc: 'Stop central hidráulica (físico)',      cat: 'Comandos' },
  
  { name: 'CMD_PULS_MANUAL',            word: 60, bit: 8, dir: 'write',  desc: 'CMD_PULS_MANUAL',              cat: 'Comandos' },
  { name: 'CMD_PULS_AUTO',              word: 60, bit: 9, dir: 'write',  desc: 'CMD_PULS_AUTO',                cat: 'Comandos' },
  { name: 'CMD_RESET_CONT_PROD',        word: 60, bit: 10, dir: 'write',  desc: 'CMD_RESET_CONT_PROD',         cat: 'Comandos' },
  { name: 'CMD_RESET_STOP_AUTO_A_CIL',  word: 60, bit: 11, dir: 'write',  desc: 'CMD_RESET_STOP_AUTO_A_CIL',   cat: 'Comandos' },
  { name: 'CMD_ABIL_START_AUTO_A_RES',  word: 60, bit: 12, dir: 'write',  desc: 'CMD_ABIL_START_AUTO_A_RES',   cat: 'Comandos' },
  { name: 'CMD_ABIL_STOP_AUTO_A_TEMPO', word: 60, bit: 13, dir: 'write',  desc: 'CMD_ABIL_STOP_AUTO_A_TEMPO',  cat: 'Comandos' },
  { name: 'CMD_ABIL_STOP_AUTO_A_CICLI', word: 60, bit: 14, dir: 'write',  desc: 'CMD_ABIL_STOP_AUTO_A_CICLI',  cat: 'Comandos' },
  { name: 'W60_BIT15_NO_USAR',          word: 60, bit: 15, dir: 'write',  desc: 'W60_BIT15_NO_USAR',           cat: 'Comandos' },
  
  // --- W61 ---
  // --- Comandos Scada en W61 elaborados por el PLC, quien los elabora y escribe en la W1 ---
  { name: 'CMD_CICLO_AUTO-MAN',         word: 61, bit: 0, dir: 'write',  desc: 'CMD_CICLO_AUTO-MAN',           cat: 'Comandos' },
  { name: 'CMD_RESET_ANOMALIE',         word: 61, bit: 1, dir: 'write',  desc: 'CMD_RESET_ANOMALIE',           cat: 'Comandos' },
  { name: 'CMD_AUTO_SIS_INGRASSAGGIO',  word: 61, bit: 2, dir: 'write',  desc: 'CMD_AUTO_SIS_INGRASSAGGIO',    cat: 'Comandos' },
  { name: 'CMD_W61_BIT3_FREE',          word: 61, bit: 3, dir: 'write',  desc: 'CMD_W61_BIT3_FREE',            cat: 'Comandos' },
  { name: 'CMD_W61_BIT4_FREE',          word: 61, bit: 4, dir: 'write',  desc: 'CMD_W61_BIT4_FREE',            cat: 'Comandos' },
  { name: 'CMD_W61_BIT5_FREE',          word: 61, bit: 5, dir: 'write',  desc: 'CMD_W61_BIT5_FREE',            cat: 'Comandos' },
  { name: 'CMD_RESISTENZE_ACCESE',      word: 61, bit: 6, dir: 'write',  desc: 'CMD_RESISTENZE_ACCESE',        cat: 'Comandos' },
  { name: 'CMD_POMPA_ACCESA',           word: 61, bit: 7, dir: 'write',  desc: 'CMD_POMPA_ACCESA',             cat: 'Comandos' },
                                                                               
  { name: 'CMD_MANUAL',                 word: 61, bit: 8, dir: 'write',  desc: 'CMD_MANUAL',                   cat: 'Comandos' },
  { name: 'CMD_START_CICLO',            word: 61, bit: 9, dir: 'write',  desc: 'CMD_START_CICLO',              cat: 'Comandos' },
  { name: 'CMD_AUTOMATICO',             word: 61, bit: 10, dir: 'write',  desc: 'CMD_AUTOMATICO',              cat: 'Comandos' },
  { name: 'CMD_STOP_CICLO',             word: 61, bit: 11, dir: 'write',  desc: 'CMD_STOP_CICLO',              cat: 'Comandos' },
  { name: 'CMD_W61_BIT12_FREE',         word: 61, bit: 12, dir: 'write',  desc: 'CMD_W61_BIT12_FREE',          cat: 'Comandos' },
  { name: 'CMD_W61_BIT13_FREE',         word: 61, bit: 13, dir: 'write',  desc: 'CMD_W61_BIT13_FREE',          cat: 'Comandos' },
  { name: 'CMD_W61_BIT14_FREE',         word: 61, bit: 14, dir: 'write',  desc: 'CMD_W61_BIT14_FREE',          cat: 'Comandos' },
  { name: 'W61_BIT15_NO_USAR',          word: 61, bit: 15, dir: 'write',  desc: 'W61_BIT15_NO_USAR',           cat: 'Comandos' },
  
  // --- W62 a W119 ---
  { name: 'RECETA_ESPESOR',             word: 62, bit: null, dir: 'write', desc: 'Ricete  Spessore',                    cat: 'recetas' },
  { name: 'RECETA_EMPUJE',              word: 63, bit: null, dir: 'write', desc: 'RECETA_EMPUJE',                       cat: 'recetas' },
  { name: 'RECETA_DISPARO',             word: 64, bit: null, dir: 'write', desc: 'RECETA_DISPARO',                      cat: 'recetas' },
  { name: 'RECETA_EXPANSION',           word: 65, bit: null, dir: 'write', desc: 'RECETA_EXPANSION',                    cat: 'recetas' },  
  { name: 'RECETA_2do_EMPUJE',          word: 66, bit: null, dir: 'write', desc: 'RECETA_2do_EMPUJE',                   cat: 'recetas' },
  { name: 'RECETA_2do_DISPARO',         word: 67, bit: null, dir: 'write', desc: 'RECETA_2do_DISPARO',                  cat: 'recetas' },
  { name: 'RECETA_2do_EXPANSION',       word: 68, bit: null, dir: 'write', desc: 'RECETA_2do_EXPANSION',                cat: 'recetas' },  
  { name: 'RECETA_DURACION_LIMP_DOSIF', word: 69, bit: null, dir: 'write', desc: 'RCTA Duracion Limpieza Dosificacion', cat: 'recetas' },  
  { name: 'RECETA_RETRASO_LIMP_DOSIF',  word: 70, bit: null, dir: 'write', desc: 'RCTA Retraso Limpieza Dosificacion',  cat: 'recetas' },
  { name: 'RETRASO_SUB_PLATO_DBLCIC',   word: 71, bit: null, dir: 'write', desc: 'Retraso subida plato cent doble cic', cat: 'recetas' }, 
  { name: 'RECETA_VASO',                word: 72, bit: null, dir: 'write', desc: 'RECETA VASO',                         cat: 'recetas' },  
  { name: 'RECETA_CICLOS_LIMP_DOSIF',   word: 73, bit: null, dir: 'write', desc: 'Ciclos de limpieza de dosificacion',  cat: 'recetas' },      
  { name: 'RECETA_TEMP_CONSIG_SUP',     word: 74, bit: null, dir: 'write', desc: 'Temperatura de consigna superior',    cat: 'recetas' },      
  { name: 'RECETA_TEMP_CONSIG_INF',     word: 75, bit: null, dir: 'write', desc: 'Temperatura de consigna inferior',    cat: 'recetas' },      
  { name: 'RECETA_NUM_FORMAS_MOLDE',    word: 76, bit: null, dir: 'write', desc: 'numero de formas en el molde',        cat: 'recetas' }, 

  { name: 'W77_FREE',                   word: 77, bit: null, dir: 'write', desc: 'W77_Free',                            cat: 'Free' },
  { name: 'W78_FREE',                   word: 78, bit: null, dir: 'write', desc: 'W78_Free',                            cat: 'Free' },
  { name: 'W79_FREE',                   word: 79, bit: null, dir: 'write', desc: 'W79_Free',                            cat: 'Free' },
  { name: 'W80_FREE',                   word: 80, bit: null, dir: 'write', desc: 'W80_Free',                            cat: 'Free' },
  { name: 'W81_FREE',                   word: 81, bit: null, dir: 'write', desc: 'W81_Free',                            cat: 'Free' },
  { name: 'W82_FREE',                   word: 82, bit: null, dir: 'write', desc: 'W82_Free',                            cat: 'Free' },
  { name: 'W83_FREE',                   word: 83, bit: null, dir: 'write', desc: 'W83_Free',                            cat: 'Free' },
  { name: 'CMD_TEMP_SPSUP',             word: 84, bit: null, dir: 'write', desc: 'CMD_TEMP_SPSUP',                      cat: 'Cmd_Temp' },
  { name: 'CMD_TEMP_SPINF',             word: 85, bit: null, dir: 'write', desc: 'CMD_TEMP_SPINF',                      cat: 'Cmd_Temp' },
  { name: 'W86_FREE',                   word: 86, bit: null, dir: 'write', desc: 'W86_Free',                            cat: 'Free' },
  { name: 'W87_FREE',                   word: 87, bit: null, dir: 'write', desc: 'W87_Free',                            cat: 'Free' },
  { name: 'W88_FREE',                   word: 88, bit: null, dir: 'write', desc: 'W88_Free',                            cat: 'Free' },
  { name: 'W89_FREE',                   word: 89, bit: null, dir: 'write', desc: 'W89_Free',                            cat: 'Free' },
  { name: 'W90_FREE',                   word: 90, bit: null, dir: 'write', desc: 'W90_Free',                            cat: 'Free' },
  { name: 'W91_FREE',                   word: 91, bit: null, dir: 'write', desc: 'W91_Free',                            cat: 'Free' },
  { name: 'W92_FREE',                   word: 92, bit: null, dir: 'write', desc: 'W92_Free',                            cat: 'Free' },
  { name: 'W93_FREE',                   word: 93, bit: null, dir: 'write', desc: 'W93_Free',                            cat: 'Free' },
  { name: 'W94_FREE',                   word: 94, bit: null, dir: 'write', desc: 'W94_Free',                            cat: 'Free' },
  { name: 'W95_FREE',                   word: 95, bit: null, dir: 'write', desc: 'W95_Free',                            cat: 'Free' },
  { name: 'W96_FREE',                   word: 96, bit: null, dir: 'write', desc: 'W96_Free',                            cat: 'Free' },
  { name: 'W97_FREE',                   word: 97, bit: null, dir: 'write', desc: 'W97_Free',                            cat: 'Free' },
  { name: 'W98_FREE',                   word: 98, bit: null, dir: 'write', desc: 'W98_Free',                            cat: 'Free' },
  { name: 'W99_FREE',                   word: 99, bit: null, dir: 'write', desc: 'W99_Free',                            cat: 'Free' },
  { name: 'W100_FREE',                  word: 100, bit: null, dir: 'write', desc: 'W100_Free',                          cat: 'Free' },
  { name: 'W101_FREE',                  word: 101, bit: null, dir: 'write', desc: 'W101_Free',                          cat: 'Free' },
  { name: 'W102_FREE',                  word: 102, bit: null, dir: 'write', desc: 'W102_Free',                          cat: 'Free' },
  { name: 'W103_FREE',                  word: 103, bit: null, dir: 'write', desc: 'W103_Free',                          cat: 'Free' },
  { name: 'W104_FREE',                  word: 104, bit: null, dir: 'write', desc: 'W104_Free',                          cat: 'Free' },
  { name: 'W105_FREE',                  word: 105, bit: null, dir: 'write', desc: 'W105_Free',                          cat: 'Free' },
  { name: 'W106_FREE',                  word: 106, bit: null, dir: 'write', desc: 'W106_Free',                          cat: 'Free' },
  { name: 'W107_FREE',                  word: 107, bit: null, dir: 'write', desc: 'W107_Free',                          cat: 'Free' },
  { name: 'W108_FREE',                  word: 108, bit: null, dir: 'write', desc: 'W108_Free',                          cat: 'Free' },
  { name: 'W109_FREE',                  word: 109, bit: null, dir: 'write', desc: 'W109_Free',                          cat: 'Free' },
  { name: 'W110_FREE',                  word: 110, bit: null, dir: 'write', desc: 'W110_Free',                          cat: 'Free' },
  { name: 'W111_FREE',                  word: 111, bit: null, dir: 'write', desc: 'W111_Free',                          cat: 'Free' },
  { name: 'W112_FREE',                  word: 112, bit: null, dir: 'write', desc: 'W112_Free',                          cat: 'Free' },
  { name: 'W113_FREE',                  word: 113, bit: null, dir: 'write', desc: 'W113_Free',                          cat: 'Free' },
  { name: 'W114_FREE',                  word: 114, bit: null, dir: 'write', desc: 'W114_Free',                          cat: 'Free' },
  { name: 'W115_FREE',                  word: 115, bit: null, dir: 'write', desc: 'W115_Free',                          cat: 'Free' },
  { name: 'W116_FREE',                  word: 116, bit: null, dir: 'write', desc: 'W116_Free',                          cat: 'Free' },
  { name: 'W117_FREE',                  word: 117, bit: null, dir: 'write', desc: 'W117_Free',                          cat: 'Free' },
  { name: 'W118_FREE',                  word: 118, bit: null, dir: 'write', desc: 'W118_Free',                          cat: 'Free' },
  { name: 'W119_FREE',                  word: 119, bit: null, dir: 'write', desc: 'W119_Free',                          cat: 'Free' },
  
];

module.exports = { tags };